spring.application.name=jwt-security-project

spring.datasource.url = jdbc:mysql://localhost:3306/jwt_security_project_db
spring.datasource.username = root
spring.datasource.password =

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

jwt.secret = koushikjwtsecurityproject0123456789
jwt.expiration = 3600000